from fpdf import FPDF
import matplotlib.pyplot as plt
import tempfile
import os

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Mineral Processing Efficiency Report', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(data, filename="report.pdf"):
    """
    Generates a PDF report with the analysis results.
    
    Args:
        data (dict): Dictionary containing results to report.
                     Expected keys: 'p80_feed', 'p80_product', 'bond_work_index', 
                                    'energy_consumption', 'screen_efficiency', 
                                    'optimization_potential'
        filename (str): Output filename.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    pdf.cell(200, 10, txt="Simulation Results", ln=True, align='L')
    pdf.ln(10)
    
    # Table-like output
    pdf.set_font("Arial", 'B', 10)
    pdf.cell(100, 10, "Parameter", 1)
    pdf.cell(90, 10, "Value", 1)
    pdf.ln()
    
    pdf.set_font("Arial", size=10)
    
    items = [
        ("Feed P80 (micrometers)", f"{data.get('p80_feed', 'N/A')}"),
        ("Product P80 (micrometers)", f"{data.get('p80_product', 'N/A')}"),
        ("Bond Work Index (kWh/t)", f"{data.get('bond_work_index', 'N/A')}"),
        ("Energy Consumption (kWh/t)", f"{data.get('energy_consumption', 'N/A')}"),
        ("Screen Efficiency (%)", f"{data.get('screen_efficiency', 'N/A') * 100:.2f}" if data.get('screen_efficiency') else "N/A"),
        ("Optimization Potential", f"{data.get('optimization_potential', 'N/A')}")
    ]
    
    for key, value in items:
        pdf.cell(100, 10, key, 1)
        pdf.cell(90, 10, str(value), 1)
        pdf.ln()
        
    pdf.ln(10)
    pdf.cell(0, 10, "Note: This report is generated by MineralProcessing-Efficiency-Tool.", 0, 1)

    try:
        pdf.output(filename)
        print(f"Report generated successfully: {filename}")
    except Exception as e:
        print(f"Error generating PDF: {e}")
